backend_api:
  REACT_APP_OPTIMUS_ANALYTICS_API: "https://minco-dch-dev06.azurewebsites.net/api/v1/process_data/"
  REACT_APP_OPTIMUS_DATA_INSIGHT_API: "https://minco-dch-dev07.azurewebsites.net/api/v1/process_data/"
  model_to_api_map:
    ca2xl: "a2"
    ca1xl: "a1"
    ma2: "ma2"
    ca0xl: "a0"
